### ISSUE TITLE
What primitives do we want for path editing?

### ISSUE THREAD

**Issue by jeizenga** [vgteam/libhandlegraph#6]
@Robin-Rounthwaite is working on a graph normalization method in VG, and it's run up against some limitations on the HandleGraph API. Specifically, he want to modify the topology of sections of graph while maintaining embedded paths. Currently, our path modification API is append only, so edits to the middle are more or less prohibited. I think we need to extend the API a bit, but we have some options for API design.

To my mind, there are two real possibilities here:
1) Allow removal and addition of single steps to the middle of the path. I like that this is a simple, low-level API that matches the level of access to the graph that we've been providing in the rest of the codebase. However, it has the downside that swapping a segment of path from one part of the graph to another may require invalid intermediate states where adjacencies in the path don't correspond to edges in the graph.

2) Create a bulk swapping method for a segment of path. This feels like a higher level API than the rest of libhandlegraph provides, but it would allow the graph normalization algorithm to avoid any invalid intermediate states.

Any thoughts? @adamnovak @glennhickey @ekg

**Comment by adamnovak** [comment]
Exposing a "rewrite-between" operation might be good, because that might be easy to implement efficiently in linked-list backends, and we want to expose efficiencies that the backends can provide. Plus, it lets you do the operation without ever having the path in a semantically invalid state. I think that rewriting the path between two steps (by replacing what's there with a new subpath **of the same base pair length**) should definitely become a virtual MutablePathHandleGraph method, probably with a default implementation in terms of lower-level operations (see below).

The whole problem would be simpler if we changed the paths API to present path regions ("extents"?). Each contiguous run of steps is identified by a path name key and a start offset. Then you can remove a step and let that split the path region into two path regions with their own start offsets, without any invalid adjacencies and without changing the coordinates along the path of anything downstream. Then you can add the new steps, and if you add the same length of material the path regions will abut one another again. Then either the path regions can be coalesced automatically, or you can make a call to weld them back together. I think these are the right operations to expose to implement the rewrite-path-between functionality, but they require amending the path API yet again to introduce another layer, and they also require a backing implementation where offsets can be efficiently calculated.

Overall, I think we should:

* Adopt the paths vs. path regions/extents distinction in the basic PathHandleGraph.
* Provide a rewrite-path-between in the basic mutable-paths interface, but do *not* provide any way to split up an extent. This ensures that implementations that do not have efficient offset computation can be used. They just have to *remember* the start offset for each extent.
* Provide some class in the hierarchy that guarantees efficient offset computation, and in the mutable-paths version of that, provide both the methods needed to split and join extents, and a default implementation of rewrite-path-between that uses them.

**Comment by jeizenga** [comment]
In order to avoid blocking @Robin-Rounthwaite, I implemented a version of this without extents for now, but it could form the basis for an extent-based implementation later. Adam and I had a discussion a while back, the upshot of which I believe was that extents will really earn their keep in representing paths in subgraphs. That wasn't really Robin's issue at this point, hence the punt. I also left off the issue of adding offsets to the interface, although I do think that would be a useful thing to have. 

Anyway, I guess I'll leave this issue open for now, since there's still some good material in here for future development.

**Comment by ekg** [comment]
In rewrite_segment, has the definition of segment_begin and segment_end been shifted back to "beginning step" and "one past end"?

If so, then, 1) I'd like to lodge a vote against this, because 2) it requires me to implement a path-specific start and end iterator and check everywhere if I've got one of those in hand or an actual path step. Right now, I have one global terminator value for the path end and reverse end.

Requiring that both start and end are actual steps in the path doesn't hurt anything, and makes the implementation much simpler. It's not STL-like, but, we're not exactly working with STL-like data structures here.

**Comment by ekg** [comment]
I think we have this sorted. Cool.
